import type { CashflowData, CounterpartyData, TimelineData, TokenExposure, HeuristicFlag } from '@cripto-ir/shared';
import { weiToEth } from '../utils/bigint.js';

export function generateMarkdownReport(
  address: string,
  data: {
    cashflow: CashflowData[];
    counterparties: CounterpartyData[];
    timeline: TimelineData[];
    tokens: TokenExposure[];
    heuristics: HeuristicFlag[];
    txCount: number;
  }
): string {
  const sections: string[] = [];

  sections.push(`# Blockchain Investigation Report\n\n**Address:** \`${address}\`\n**Generated:** ${new Date().toISOString()}\n**Total Transactions:** ${data.txCount}\n`);

  // Summary
  sections.push(`## Summary\n`);
  const totalInflow = data.cashflow.reduce((sum, m) => sum + BigInt(m.inflow), 0n);
  const totalOutflow = data.cashflow.reduce((sum, m) => sum + BigInt(m.outflow), 0n);
  sections.push(`- **Total Inflow:** ${weiToEth(totalInflow.toString())} ETH`);
  sections.push(`- **Total Outflow:** ${weiToEth(totalOutflow.toString())} ETH`);
  sections.push(`- **Net Flow:** ${weiToEth((totalInflow - totalOutflow).toString())} ETH`);
  sections.push(`- **Unique Counterparties:** ${data.counterparties.length}`);
  sections.push(`- **Tokens Interacted:** ${data.tokens.length}\n`);

  // Heuristic Flags
  if (data.heuristics.length > 0) {
    sections.push(`## Suspicious Activity Flags\n`);
    for (const flag of data.heuristics) {
      const icon = flag.severity === 'high' ? '🔴' : flag.severity === 'medium' ? '🟡' : '🟢';
      sections.push(`### ${icon} ${flag.title} (${flag.severity})\n${flag.description}\n`);
    }
  }

  // Cashflow
  if (data.cashflow.length > 0) {
    sections.push(`## Monthly Cashflow\n`);
    sections.push(`| Month | Inflow (ETH) | Outflow (ETH) | Net (ETH) |`);
    sections.push(`|-------|-------------|--------------|-----------|`);
    for (const m of data.cashflow) {
      sections.push(`| ${m.month} | ${weiToEth(m.inflow)} | ${weiToEth(m.outflow)} | ${weiToEth(m.netflow)} |`);
    }
    sections.push('');
  }

  // Top Counterparties
  if (data.counterparties.length > 0) {
    sections.push(`## Top Counterparties\n`);
    sections.push(`| Address | Txns | Inflow (ETH) | Outflow (ETH) |`);
    sections.push(`|---------|------|-------------|--------------|`);
    for (const cp of data.counterparties.slice(0, 20)) {
      sections.push(`| \`${cp.address.slice(0, 10)}...\` | ${cp.tx_count} | ${weiToEth(cp.total_in)} | ${weiToEth(cp.total_out)} |`);
    }
    sections.push('');
  }

  // Token Exposure
  if (data.tokens.length > 0) {
    sections.push(`## Token Exposure\n`);
    sections.push(`| Token | Transfers | Symbol |`);
    sections.push(`|-------|-----------|--------|`);
    for (const t of data.tokens.slice(0, 20)) {
      sections.push(`| ${t.token_name} | ${t.transfer_count} | ${t.token_symbol} |`);
    }
    sections.push('');
  }

  // Timeline
  if (data.timeline.length > 0) {
    sections.push(`## Activity Timeline\n`);
    sections.push(`| Period | Transactions | Counterparties | Volume (ETH) |`);
    sections.push(`|--------|-------------|----------------|-------------|`);
    for (const t of data.timeline) {
      sections.push(`| ${t.period} | ${t.tx_count} | ${t.unique_counterparties} | ${weiToEth(t.volume)} |`);
    }
    sections.push('');
  }

  sections.push(`---\n*Report generated by Cripto_ir Investigation Tool*`);

  return sections.join('\n');
}
